      SUBROUTINE CPYFIL(NFILES,LFN1,LFN2)
C
C COPIES NFILES FILES FROM LFN1 TO LFN2 INSERTING CARRIAGE CONTROL
C
      CHARACTER BUF*80
C
      DO 100 I=1,NFILES
10       CONTINUE
            READ (LFN1,'(A)',END=999) BUF
CHAR        READ (LFN1,'(A)',END=20) BUF
            IF (BUF(:5).EQ.'<EOF>' .OR. BUF(:6).EQ.' <EOF>') GO TO 20
            WRITE (LFN2,'(1X,A)') BUF
         GO TO 10
20       WRITE (LFN2,*) '<EOF>'
100   CONTINUE
C
999   RETURN
      END
      SUBROUTINE ADVFIL(LFN,ICOUNT)
C
C ADVANCES UNIT 'LFN' BY 'ICOUNT' LOGICAL FILES
C
      CHARACTER STRING*6
C
      DO 100 I=1,ICOUNT
10       CONTINUE
            READ (LFN,'(A)',END=800) STRING
CHAR        READ (LFN,'(A)',END=100) STRING
            IF (STRING.EQ.'<EOF> ' .OR. STRING.EQ.' <EOF>') GO TO 100
         GO TO 10
100   CONTINUE
      GO TO 999
C
800   call intpr('ERROR: END OF FILE ENCOUNTERED BEFORE "<EOF>"',-1,0,0)
      STOP
C
999   RETURN
      END
      SUBROUTINE ADVREC(LFN,ICOUNT)
C
C ADVANCES UNIT 'LFN' BY 'ICOUNT' RECORDS, OR UNTIL EOF
C
      DO 100 I=1,ICOUNT
         READ (LFN,*,END=900)
100   CONTINUE
C
900   RETURN
      END
