      SUBROUTINE INPUT3b(NALL,PAR,XINIT,XALL,ITP,
     +   LFNJOB,LFNTER,H,TOL,TRUPB,INLC,IVAR,IHESS,IHX,IQOB,IVERB,ISTAT)
C---
C--- INITIALIZES PA, IT AND ASSOCIATED VARIABLES FOR ALMINI,
C--- CALLS RDPAIT FOR STARTING VALUES.
C---
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)

      PARAMETER   (NGROUP=6)

      CHARACTER   PAR(*)*(*)
      DIMENSION   XINIT(NALL), XALL(NALL), ITP(NALL)

C DEFAULTS FOR ALMINI

      H      = .0001
      TOL    = .0001
      TRUPB  = 10.*SQRT(H)
      INLC   = 1
      IVAR   = 1
      IHESS  = 0
      IHX    = 0
c      IHX    = 1
      IQOB   = 0
      IVERB  = 2

C ITERATED AND EQUAL PARAMETERS FLAGS

      DO 200 I=1,NALL
         ITP(I)  = 0
200   CONTINUE

C READ 'PA' AND 'IT' CARDS FROM JOB FILE
C (ISTAT = -1 INDICATES END OF JOB FILE)

      CALL RDPAIT(NALL,PAR,XINIT,XALL,ITP,
     +   LFNJOB,LFNTER,H,TOL,TRUPB,INLC,IVAR,IVERB,ISTAT)

      IF (ISTAT .NE. 0) GO TO 900

C WRITE INITIAL VALUES TO TERSE

      NPARM = NALL - 2*NGROUP
      CALL WRINIT(LFNTER,H,TRUPB,TOL,PAR,XALL,ITP,1,7)
      CALL WRINIT(LFNTER,H,TRUPB,TOL,PAR,XALL,ITP,8,NPARM)
      CALL WRINIT(LFNTER,H,TRUPB,TOL,PAR,XALL,ITP,NPARM+1,NALL)

900   RETURN
      END
