C FILE "TX.INC" ========================================================
C COMMON /TX/: CONTAINS DATA STRUCTURES USED IN DATA TRANSFORMATIONS
C
C VARIABLES:
C     ITOKEN -- LIST OF POINTERS TO OPERATORS AND OPERANDS
C     NTOKEN -- CURRENT NUMBER OF ELEMENTS IN TOKEN
C     MAXTOK -- DIMENSION OF ITOKEN
C     RCONST -- LIST OF OPERANDS (NUMERIC CONSTANTS)
C     NCONST -- CURRENT NUMBER OF ELEMENTS IN CONST
C     MAXCON -- DIMENSION OF RCONST
C     IOPTOR -- LIST OF OPERATORS
C     NOPTOR -- CURRENT NUMBER OF ELEMENTS IN OPTOR
C     MAXOPT -- DIMENSION OF IOPTOR
C
      PARAMETER (MAXTOK=200, MAXCON=100, MAXOPT=100)

      DOUBLE PRECISION  RCONST

      COMMON /TX/    ITOKEN(MAXTOK),
     +               RCONST(MAXCON),
     +               IOPTOR(3,MAXOPT),
     +               NTOKEN,
     +               NCONST,
     +               NOPTOR

C END OF FILE "TX.INC" =================================================
