%% \VignetteIndexEntry{Drawing pedigree diagrams with R and graphviz}
%% \Vignettekeywords{pedigree diagram}
%% \VignettePackage{gap}

\documentclass[12pt]{article}
\usepackage{Sweave,hyperref,pdfpages}
\usepackage{url}
\usepackage{amsmath,epsfig}
\usepackage{graphicx}
\usepackage[authoryear,round]{natbib}
\bibliographystyle{plainnat}

\begin{document}

\includepdf[pages=-,width=8.5in]{peddraw.pdf}\label{rnews}.

\end{document}
