vignettes/ChangeLog.txt: $(HOME)/R/gap/ChangeLog
	cp $(HOME)/R/gap/ChangeLog vignettes/ChangeLog.txt

vignettes/gap-manual.pdf: $(HOME)/R/gap.Rcheck/gap-manual.pdf
	cp $(HOME)/R/gap.Rcheck/gap-manual.pdf vignettes/

vignettes/shinygap.html: /rds/project/rds-4o5vpvAowP0/software/R/gap/doc/shinygap.html
	cp /rds/project/rds-4o5vpvAowP0/software/R/gap/doc/shinygap.html vignettes/

vignettes/gap.examples.pdf: /rds/project/rds-4o5vpvAowP0/software/R/gap.examples/doc/gap.examples.pdf
	cp /rds/project/rds-4o5vpvAowP0/software/R/gap.examples/doc/gap.examples.pdf vignettes/
