vignettes/ChangeLog.txt: ~/R/gap/ChangeLog
	cp -p ~/R/gap/ChangeLog vignettes/ChangeLog.txt

vignettes/gap-manual.pdf: ~/R/gap.Rcheck/gap-manual.pdf
	cp -p ~/R/gap.Rcheck/gap-manual.pdf vignettes/

vignettes/shinygap.html: ~/R/gap/doc/shinygap.html
	cp -p ~/R/gap/doc/shinygap.html vignettes/
